name: Generate flattened IATI data

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 5 * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download data
        run: |
          wget https://www.dropbox.com/s/kkm80yjihyalwes/iati_dump.zip?dl=1 -O iati-data-dump.zip
          unzip iati-data-dump.zip -d iati-data-dump
      - name: Generate data
        run: |
          python generate.py
        env:
          MORPH_IO_API_KEY: ${{ secrets.MORPH_IO_API_KEY }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/xlsx
          force_orphan: true